version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: app-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./infra/db/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: app-api
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      PORT: ${APP_PORT}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:${APP_PORT}"
    restart: unless-stopped
#
#  frontend:
#    build:
#      context: ./apps/frontend
#      dockerfile: Dockerfile
#      args:
#        NEXT_PUBLIC_BACKEND_URL: ${BACKEND_URL}
#    container_name: app-front
#    depends_on:
#      backend:
#        condition: service_started
#    ports:
#      - "3000:3000"
#    restart: unless-stopped

volumes:
  db-data: